const sensors = [
  {
    id: 1,
    name: "Gresham Community Site",
    type: "QuantAQ",
    location: "Outdoor",
    aqi: 35,
    temperature: 63,
    humidity: 48,
    status: "good",
    lat: 45.5001,
    lng: -122.4302,
  },
  {
    id: 2,
    name: "East Portland Community Site",
    type: "QuantAQ",
    location: "Outdoor",
    aqi: 75,
    temperature: 66,
    humidity: 58,
    status: "moderate",
    lat: 45.5083,
    lng: -122.5031,
  },
  {
    id: 3,
    name: "Lents Neighborhood",
    type: "QuantAQ",
    location: "Outdoor",
    aqi: 120,
    temperature: 68,
    humidity: 42,
    status: "sensitive",
    lat: 45.4720,
    lng: -122.5773,
  },
  {
    id: 4,
    name: "Cully Neighborhood",
    type: "QuantAQ",
    location: "Outdoor",
    aqi: 165,
    temperature: 71,
    humidity: 55,
    status: "unhealthy",
    lat: 45.5620,
    lng: -122.5931,
  },
  {
    id: 5,
    name: "Parkrose Neighborhood",
    type: "QuantAQ",
    location: "Outdoor",
    aqi: 230,
    temperature: 74,
    humidity: 61,
    status: "veryunhealthy",
    lat: 45.5537,
    lng: -122.5445,
  },
  {
    id: 6,
    name: "Hazelwood Neighborhood",
    type: "QuantAQ",
    location: "Outdoor",
    aqi: 320,
    temperature: 69,
    humidity: 53,
    status: "hazardous",
    lat: 45.5145,
    lng: -122.5359,
  },
];

export default sensors;